### ISSUE TITLE
Error 500 multiple resons in docker image

### ISSUE THREAD

**Issue by GregpryA** [Crivaledaz/Mattermost-LDAP#102]
Fresh install in docker mode.
1. Error 500
nginx log shows that 'ssl on' deprecated in oauth.conf (fixed with editing)
nginx log shows duplicate localhost server names (fixed with making volume for default.conf with another server_name)

Now - nginx starts fine, but error 500 when hitting 'GitLab' button is still here.

docker logs <docker-php-psql container id> showing:

NOTICE: PHP message: PHP Warning:  require_once(config_db.php): Failed to open stream: No such file or directory in /var/www/html/oauth/server.php on line 7
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Failed opening required 'config_db.php' (include_path='.:/usr/local/lib/php') in /var/www/html/oauth/server.php:7
Stack trace:
#0 /var/www/html/oauth/authorize.php(11): require_once()
#1 {main}
  thrown in /var/www/html/oauth/server.php on line 7
192.168.112.4 -  30/Mar/2023:12:25:37 +0000 "GET /oauth/authorize.php" 500

**Comment by Crivaledaz** [comment]
Hi,

Thank you for your feedback and suggestion to fix the error 500 raised by NGINX.

Have you tried the Demo version with docker-compose? Does it work for you?

In the Demo version, SSL is disabled (commented out in the configuration), so the issues you are experiencing with NGINX should not exist in the Demo. If the Demo is working for you, I would suggest deploying Mattermost-LDAP in HTTP mode initially. Once it works in HTTP mode, you can then focus on configuring HTTPS.

According to your Docker logs, it seems that the PHP server cannot open the database configuration file config_db.php. Please check that this file exists in your working directory and is derived from [`config_db.php.example`](https://github.com/Crivaledaz/Mattermost-LDAP/blob/master/oauth/config_db.php.example). The file `config_db.php` should be visible in your container (mounted as a volume, as all the `oauth` should be) and readable by the PHP user.

Additionally, I have pushed a fix for the database init script on the master branch. Please pull the changes and try again.

Please let me know if your issue is resolved.

Regards.

**Comment by GregpryA** [comment]
Dear Sir, thank you for the reply.

First of all: I definitely pulled Demo version, because it was the only one docker-based version I was able to find. Sorry, I've been totally M$ and Cisco man for decades until February. So *nix and Git is quite terra incogints for me. Again, sorry - if there is not-Demo docker based version - I wasn't able to find it. Please teach me, how to get it.

As for errors. No worries with HHTPS. As it was said, I managed to owercome this problem. But my fix was definitely not good, Breaking the great idea of flexibility and pkanform-indepebdense of docker concept. Plus my solution is not user-friendly.

But my main pain is second bug, As I said - the file is not existing within my docker. In fact - even location does not exist. Maybe it is because I was not able to find not-demo version with all features? That's possible. Or "dockerised" version was composed not in full. Dont know, who's fault here. Need help. : -))

**Comment by GregpryA** [comment]
Found out, that it was my fault in las part. I missed to rename config_db and config_ldap files, which likely lead to not full expansion of DB and other related files. You can safely close the case.

**Comment by tsarkovan** [comment]
Hello! I try to use v2.1 branch in docker. And i got error 500. In logs i see
`db-1     | 2024-10-23 08:22:29.254 UTC [33] ERROR:  relation "oauth_clients" does not exist at character 15
db-1     | 2024-10-23 08:22:29.254 UTC [33] STATEMENT:  SELECT * from oauth_clients where client_id = $1
php-1    | 172.18.0.4 -  23/Oct/2024:08:22:29 +0000 "GET /oauth/authorize.php" 500
php-1    | NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oauth_clients" does not exist
php-1    | LINE 1: SELECT * from oauth_clients where client_id = $1
php-1    |                       ^ in /var/www/html/oauth/OAuth2/Storage/Pdo.php:126
php-1    | Stack trace:
php-1    | #0 /var/www/html/oauth/OAuth2/Storage/Pdo.php(126): PDOStatement->execute()
php-1    | #1 /var/www/html/oauth/OAuth2/Controller/AuthorizeController.php(211): OAuth2\Storage\Pdo->getClientDetails()
php-1    | #2 /var/www/html/oauth/OAuth2/Server.php(413): OAuth2\Controller\AuthorizeController->validateAuthorizeRequest()
php-1    | #3 /var/www/html/oauth/authorize.php(22): OAuth2\Server->validateAuthorizeRequest()
php-1    | #4 {main}
php-1    |   thrown in /var/www/html/oauth/OAuth2/Storage/Pdo.php on line 126
`

Maybe neeed to do somthing with DB?
