### ISSUE TITLE
authorize.php error 500

### ISSUE THREAD

**Issue by demogorgonz** [Crivaledaz/Mattermost-LDAP#91]
**Describe the bug**

**To Reproduce**
1. run the demo, open http://localhost:8065 and try to login
2. See error : 

```
http://localhost/oauth/authorize?response_type=code&client_id=123456789abcdef123456789abcdef&redirect_uri=http%3A%2F%2Flocalhost%2Fsignup%2Fgitlab%2Fcomplete&state=eyJhY3Rpb24iOiJsb2dpbiIsImlzTW9iaWxlIjoiZmFsc2UiLCJ0b2tlbiI6InhycDgzN3B5cTEzcmRkODRqbnBkYXhpeWhjb3QxdGc0ZHNqN2RtMzQ5YWpxNXpyaW56M3JkYnM4emFneHR5eDkifQ%3D%3D

This page isn’t workinglocalhost is currently unable to handle this request.
HTTP ERROR 500
```

Exact steps:

```
git clone https://github.com/Crivaledaz/Mattermost-LDAP
cd Mattermost-LDAP/Demo
cp -p ../oauth/config_db.php.example ../oauth/config_db.php
cp -p ../oauth/LDAP/config_ldap.php.example ../oauth/LDAP/config_ldap.php
docker-compose up -d
```

Seems like the demo is not working. P.S i have generated the certs.

**Comment by demogorgonz** [comment]
Just tried a fresh demo, copied the configs :

```
cp -p ../oauth/config_db.php.example ../oauth/config_db.php
cp -p ../oauth/LDAP/config_ldap.php.example ../oauth/LDAP/config_ldap.php
```

from Demo folder run:

`docker-compose up -d`

___

- Opened localhost (mattermost) which auto pointed to URL `http://localhost/signup_user_complete`
- Gitlab SSO button points to `http://localhost/oauth/gitlab/signup`
- Upon clicking i get redirected to URL `http://localhost/oauth/authorize?response_type=code&client_id=123456789abcdef123456789abcdef&redirect_uri=http%3A%2F%2Flocalhost%2Fsignup%2Fgitlab%2Fcomplete&state=eyJhY3Rpb24iOiJzaWdudXAiLCJ0b2tlbiI6IjU5aGphcmJybW1tNWlvZWM2Z2I2aGVkb3o0N2sxM2NuaDMxYnp4aWV3cTdnb21paDh4Znptbm9jaGtzd291ZWcifQ%3D%3D`

Logs from php container:

```
NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] FATAL:  role "oauth" does not exist in /var/www/html/oauth/OAuth2/Storage/Pdo.php:67
172.18.0.6 -  26/Apr/2022:12:04:13 +0000 "GET /oauth/authorize.php" 500
Stack trace:
#0 /var/www/html/oauth/OAuth2/Storage/Pdo.php(67): PDO->__construct()
#1 /var/www/html/oauth/server.php(14): OAuth2\Storage\Pdo->__construct()
#2 /var/www/html/oauth/authorize.php(11): require_once('...')
#3 {main}
  thrown in /var/www/html/oauth/OAuth2/Storage/Pdo.php on line 67

```


Going to http://localhost/oauth/index.php and logging in with `jdoe/test1234` works. 

I have tried to expose DB on host port, and instrcuted in config to connect to my IP 192.168.1.7.

From php container i have tried telnet too to the DB:
```
root@6171404260d0:/var/www/html# telnet 192.168.1.7 5432
Trying 192.168.1.7...
Connected to 192.168.1.7.
Escape character is '^]'.

```

Further inspecting logs of DB, i saw that initialization failed due to `^M` characters, quick dos2unix on init_postgres.sh & config_init.sh.example in db_init folder fixed it (had to recreate containers/purge db volume). Demo is working for me currently on Windows & Docker.

Next thing is to try same thing but on mattermost server with AD.

**Comment by demogorgonz** [comment]
Ok i have found solution for my setup, i was using Mattermost-LDAP behind reverse proxy as seperate domain "auth.example.com"

Had to add to nginx location block:

```
proxy_set_header Origin "";
error_page  405     =200 $uri;

```

Since nginx was returning `405` on POST request.
